// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api.Data;

namespace api.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.6");

            modelBuilder.Entity("api.Models.AppUserDetail", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("Biodata")
                        .HasColumnType("text");

                    b.Property<string>("Birthplace")
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<string>("Contactno")
                        .HasColumnType("text");

                    b.Property<string>("Designation")
                        .HasColumnType("text");

                    b.Property<string>("Dob")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<string>("Publications")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.Property<DateTime>("createdate")
                        .HasColumnType("datetime");

                    b.Property<string>("createdby")
                        .HasColumnType("text");

                    b.Property<ulong>("status")
                        .HasColumnType("bit")
                        .HasColumnName("status");

                    b.HasKey("UserId");

                    b.ToTable("UsersDetail");
                });

            modelBuilder.Entity("api.Models.AppUserDetailHistory", b =>
                {
                    b.Property<DateTime>("logdate")
                        .HasColumnType("datetime");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("Biodata")
                        .HasColumnType("text");

                    b.Property<string>("Birthplace")
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<string>("Contactno")
                        .HasColumnType("text");

                    b.Property<string>("Designation")
                        .HasColumnType("text");

                    b.Property<string>("Dob")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Publications")
                        .HasColumnType("text");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("createdate")
                        .HasColumnType("datetime");

                    b.Property<string>("createdby")
                        .HasColumnType("text");

                    b.Property<ulong>("status")
                        .HasColumnType("bit")
                        .HasColumnName("status");

                    b.HasKey("logdate");

                    b.ToTable("UsersDetailHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
